/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 禁用 SMTC
 *
 * ### Errors
 *
 * 会在调用 Windows API 失败时抛出错误，一般都是系统版本过低的原因
 */
export declare function disableSmtc(): void

/**
 * 启用 SMTC
 *
 * ### Errors
 *
 * 会在调用 Windows API 失败时抛出错误，一般都是系统版本过低的原因
 */
export declare function enableSmtc(): void

/**
 * 初始化插件
 *
 * ### 参数
 *
 * * `log_dir` - 要把日志文件保存到的路径
 *
 * ### Errors
 *
 * 可能会在日志初始化失败，或者 SMTC 初始化失败时 (一般都是系统版本过低的原因) 抛出错误
 *
 * ### 备注
 *
 * 如果其他 Windows API 调用失败，则只会打印日志并静默失败
 */
export declare function initialize(logDir: string): void

export interface MetadataParam {
  songName: string
  authorName: string
  albumName: string
  /** 只用于 SMTC 更新 */
  coverData?: Buffer
  /** 会以 "NCM-{ID}" 的格式上传到 SMTC 的 “流派” 字段 */
  ncmId?: number
}

export declare enum PlaybackStatus {
  Playing = 0,
  Paused = 1
}

export interface PlayModePayload {
  isShuffling: boolean
  repeatMode: RepeatMode
}

export interface PlayStatePayload {
  status: PlaybackStatus
}

/**
 * 注册 SMTC 事件回调 (上一首、下一首、暂停、播放等)
 *
 * ### 参数
 *
 * `(event: SmtcEvent) => void`
 *
 * ### Errors
 *
 * 如果 N-API 创建线程安全函数失败，会抛出错误。通常不应该发生，除非 JS 环境已经销毁了
 */
export declare function registerEventHandler(callback: (arg: SmtcEvent) => void): void

export declare enum RepeatMode {
  None = 0,
  Track = 1,
  List = 2
}

/** 关闭插件，清理资源 */
export declare function shutdown(): void

export interface SmtcEvent {
  type: SmtcEventType
  positionMs?: number
}

export declare enum SmtcEventType {
  Play = 0,
  Pause = 1,
  Stop = 2,
  NextSong = 3,
  PreviousSong = 4,
  ToggleShuffle = 5,
  ToggleRepeat = 6,
  Seek = 7
}

export interface TimelinePayload {
  /** 单位是毫秒 */
  currentTime: number
  /** 单位是毫秒 */
  totalTime: number
}

/**
 * 更新歌曲元数据
 *
 * 同时也会更新 Discord 的元数据 (如果启用了 Discord RPC)
 *
 * ### 备注
 *
 * 更新 Discord RPC 的元数据时，必须提供 `original_cover_url`
 */
export declare function updateMetadata(payload: MetadataParam): void

/**
 * 更新播放模式
 *
 * ### 备注
 *
 * 只会更新 SMTC 的信息
 */
export declare function updatePlayMode(payload: PlayModePayload): void

/**
 * 更新播放状态 (播放/暂停)
 *
 * 同时也会更新 Discord 的播放状态 (如果启用了 Discord RPC)
 */
export declare function updatePlayState(payload: PlayStatePayload): void

/**
 * 更新进度信息
 *
 * 同时也会更新 Discord 的进度信息 (如果启用了 Discord RPC)
 *
 * ### 备注
 *
 * Discord RPC 实现的进度更新有节流，调用此函数无需担心 Discord RPC 的速率限制
 */
export declare function updateTimeline(payload: TimelinePayload): void
