name: 遇到问题
description: 关于使用过程中遇到的问题
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ---
        在此之前，我们默认你已经知道该如何提问。简而言之，**你要精确地描述问题并提供充足的信息**

        此外，如果需要，你可以使用 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> 打开开发者工具为我们提供信息

  - type: checkboxes
    validations:
      required: false
    attributes:
      label: "检查清单"
      description: |
        我们需要了解一些信息，你需要检查下面的检查项 <br />
        **这里并不是每一个检查项都必要，根据你的真实情况勾选即可**
      options:
        - label: "我已检索仓库中所有的 Issues，确保我**没有重复提交问题**；或有相似 Issue，但我觉得我的情况不包含在那个相似 Issue 之内"
        - label: "我已经找到了可以复现这个问题的方法，并且写在了下面的「具体信息」中"
        - label: "此问题可以在我的设备和当前环境中**稳定复现**"
        - label: "此问题可以在最新版本 (Latest Release) 中复现"
        - label: "此问题是在我更新到当前版本后**才**出现的"

  - type: dropdown
    validations:
      required: true
    attributes:
      label: "是网页端还是客户端"
      options:
        - "客户端"
        - "网页端"
      default: 0

  - type: input
    validations:
      required: true
    attributes:
      label: "当前系统环境"
      placeholder: "如：Windows 11"

  - type: input
    validations:
      required: false
    attributes:
      label: "当前 Node.js 及 npm 版本"
      placeholder: "如：v18.16.0 / v9.6.7 (选填)"

  - type: input
    validations:
      required: true
    attributes:
      label: "当前版本"
      description: |
        填写关于软件里的或 Releases 中版本号即可 <br />
        如果是自行构建或从 GitHub Actions 下载的开发版，还需要提供 Commit ID
      placeholder: "如：v1.0.0"

  - type: textarea
    id: other
    attributes:
      label: "具体信息"
      description: |
        请填写完整的复现步骤和遇到的问题，还请尽量提供所有可能的信息，提供包括但不限于：

         - 分步的复现步骤，可以使用 `1. xxx` (换行) `2. xxx` 的格式
         - 截图（如果结合复现步骤还是无法详细表述，甚至可以录屏）
         - 开发者工具中的：控制台输出报错、网络请求等
         - 出现问题的在线歌曲链接、出现问题的文件（本地歌曲、歌词等）的下载链接

        等信息，以更好地帮助我们解决你的问题
      placeholder: "请填写具体的复现步骤和遇到的问题"
