/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 禁用 Discord RPC
 *
 * 断开 Discord 连接并清除 Rich Presence 显示
 */
export declare function disable(): void

/** Discord 配置参数 */
export interface DiscordConfigPayload {
  /** 暂停时是否显示 */
  showWhenPaused: boolean
  /** 显示模式 */
  displayMode?: DiscordDisplayMode
}

/**
 * Discord 显示模式枚举
 * 控制 Discord 左下角 "正在听 - XXX" 的显示内容
 */
export declare enum DiscordDisplayMode {
  /** 仅歌曲名：显示为 "正在听 {歌曲名}" */
  Name = 0,
  /** 仅播放状态：显示为 "正在听 `SPlayer`" */
  State = 1,
  /** 完整信息：显示为 "正在听 {歌曲名} - {歌手}" */
  Details = 2
}

/** Discord 元数据参数 */
export interface DiscordMetadataParam {
  /** 歌曲名称 */
  songName: string
  /** 艺术家/作者名称 */
  authorName: string
  /** 专辑名称 */
  albumName: string
  /** `HTTP URL` 用于封面显示 */
  originalCoverUrl?: string
  /** 歌曲时长（毫秒） */
  duration?: number
  /** 网易云音乐 ID，用于生成链接 */
  ncmId?: number
}

/** Discord 播放状态参数 */
export interface DiscordPlayStateParam {
  /** `"Playing"` 或 `"Paused"` */
  status: string
}

/** Discord 时间轴参数 */
export interface DiscordTimelineParam {
  /** 当前播放时间（毫秒） */
  currentTime: number
  /** 总时长（毫秒） */
  totalTime: number
}

/**
 * 启用 Discord RPC
 *
 * 开始尝试连接 Discord 客户端并显示 Rich Presence
 */
export declare function enable(): void

/**
 * 初始化 Discord RPC 模块
 *
 * 启动后台线程处理 Discord IPC 通信
 * # Errors
 *
 * Returns an error if the background thread cannot be spawned.
 */
export declare function initialize(): void

/**
 * 关闭 Discord RPC 模块
 *
 * 停止后台线程并断开 Discord 连接
 */
export declare function shutdown(): void

/**
 * 更新 Discord RPC 配置
 *
 * ### 参数
 *
 * * `payload` - 包含配置选项的参数
 */
export declare function updateConfig(payload: DiscordConfigPayload): void

/**
 * 更新 Discord RPC 元数据
 *
 * ### 参数
 *
 * * `payload` - 包含歌曲信息的元数据
 */
export declare function updateMetadata(payload: DiscordMetadataParam): void

/**
 * 更新 Discord RPC 播放状态
 *
 * ### 参数
 *
 * * `payload` - 包含播放状态的参数 ("Playing" or "Paused")
 */
export declare function updatePlayState(payload: DiscordPlayStateParam): void

/**
 * 更新 Discord RPC 时间轴
 *
 * ### 参数
 *
 * * `payload` - 包含当前播放时间和总时长的参数
 */
export declare function updateTimeline(payload: DiscordTimelineParam): void
